import Image from "next/image"

import hamster from "../../public/hamster.png"

const About = () => {
    return (
        <div className="bg-[#0052FE] p-4">
            <div className="rounded-lg bg-[#0F212E] border border-[#8D969C] p-4 sm:p-12">
                <div className="grid grid-cols-1 md:grid-cols-6 gap-3 items-center mb-8">

                    <div className="col-span-4">
                        <h2 className="text-3xl text-white my-3 mb-4">About</h2>
                        <p className="text-white">Welcome to the future of entertainment, where adrenaline meets adorable in the world of hamster betting. Get ready to experience the thrill of the race like never before as we dive into the coolest, most exhilarating betting platform on the market.</p>
                        <br />
                        <p className="text-white">Picture this: tiny, furry athletes racing at lightning speed towards the finish line, cheered on by fans from around the globe. That&apos;s the magic of hamster racing – a spectacle so cool, it&apos;s impossible to look away. With its unique blend of cuteness and competitiveness, hamster racing has captured the hearts of millions, making it the coolest sport on Earth by far.</p>
                    </div>

                    <div className="col-span-2">
                        <Image src={hamster} alt="hamster" className="max-w-full" />
                    </div>
                </div>

                <h2 className="my-4 text-white text-2xl">How it Works</h2>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="bg-[#1A2C38] rounded-md p-4 text-slate-300">
                        <h3 className="text-lg my-3 text-slate-200">Cool as Ice</h3>
                        <p>So, how does the coolest betting game on the planet actually work? It&apos;s simple, really. Just pick one of the four super-cool hamsters competing in the race, place your bets, and get ready to witness the coolest showdown of all time. With dynamic odds and non-stop action, every race is a thrill ride from start to finish.</p>
                    </div>

                    <div className="bg-[#1A2C38] rounded-md p-4 text-slate-300">
                        <h3 className="text-lg my-3 text-slate-200">Claim Your Cool Rewards</h3>
                        <p>But the coolness doesn&apos;t stop there. Oh no, we&apos;ve got something even cooler in store – revenue sharing! That&apos;s right, just by holding $HAMS tokens, you can claim your share of the revenue generated by the platform. The more tokens you hold, the cooler your rewards – it&apos;s that easy.</p>
                    </div>

                </div>
            </div>

        </div>
    )
}

export default About